swagger: "2.0"
info:
  description: "This is the API for Arthur Schnitzler, Hermann Bahr: Briefwechsel, Materialien, Dokumente 1891–1931 (HBAS). You can find out more about the Edition at [bahrschnitzler.acdh.oeaw.ac.at](https://bahrschnitzler.acdh.oeaw.ac.at) or [github.com/martinantonmueller/Hermann-Bahr_Arthur-Schnitzler](https://github.com/martinantonmueller/Hermann-Bahr_Arthur-Schnitzler).      Remove this later: `Code`"
  version: "1.0.0"
  title: "hbas API"
  termsOfService: "https://bahrschnitzler.acdh.oeaw.ac.at/impressum.html"
  contact:
    email: "ingo.boerner@oeaw.ac.at"
  license:
    name: "Distributed under a MIT license"
    url: "https://opensource.org/licenses/MIT"
host: "localhost:8080"
basePath: "/exist/apps/hbas/api/v1.0"
tags:
- name: "doc"
  description: "Methods about documents"
- name: "entity"
  description: "Methods about entities"
schemes:
- "https"
- "http"
paths:
  /testme:
    get:
      summary: "tests, if swagger and the api can communicate"
      produces: 
      - "application/xml"
      responses:
        202:
          description: "successful operation"
          schema:
            $ref: '#/definitions/ApiResponse'
  /doc/{docId}/about.tei:
    get:
      tags:
      - "doc"
      summary: "Get tei:teiHeader (Metadata) of a Document"
      produces:
      - "application/xml"
      parameters: 
      - name: "docId"
        in: "path"
        description: "ID of the document to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid id supplied"
        404:
          description: "document not found"  
  /doc/{docId}/about.rdf:
    get:
      tags: 
      - "doc"
      summary: "Get Metadata about a document"
      produces:
      - "application/rdf+xml"
      parameters:
      - name: "docId"
        in: "path"
        description: "ID of the document to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid id supplied"
        404:
          description: "document not found"
  /doc/{docId}/mentions.rdf:
    get:
      tags:
      - "doc"
      summary: "Get entities mentioned in a document"
      produces:
      - "application/rdf+xml"
      parameters:
      - name: "docId"
        in: "path"
        description: "ID of the document"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400: 
          description: "invalid id supplied"
        404:
          description: "document not found"
  /entity/{entityId}/about.tei:
    get:
      tags:
      - "entity"
      summary: "Get TEI-Encoded Metadata on the Entity"
      produces:
      - "application/xml"
      parameters: 
      - name: "entityId"
        in: "path"
        description: "ID of the entity to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid id supplied"
        404:
          description: "document not found"
  /entity/{entityId}/about.rdf:
    get:
      tags:
      - "entity"
      summary: "Get Metadata about an entity (person, place, organization, work)"
      produces:
      - "application/rdf+xml"
      parameters:
      - name: "entityId"
        in: "path"
        description: "ID of the entity to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid id supplied"
        404:
          description: "document not found"
definitions:
  ApiResponse:
    type: "object"
externalDocs:
  description: "About the ACDH"
  url: "http://acdh.oeaw.ac.at"